version: "3.8"
services:
  webclipper:
    build: .
    container_name: webclipper
    ports:
      - "9069:9069"
    volumes:
      - webclipper_data:/data
      - /share/recordings:/mnt/recordings
    restart: unless-stopped

volumes:
  webclipper_data:
